services:
  netbox-exporter:
    image: netbox-exporter
    container_name: netbox-exporter
    restart: unless-stopped

    environment:
      NETBOX_URL: https://netbox.example.local
      NETBOX_TOKEN: xxxxxxxxxxxxxxxxx